# metadata specialised for each experiment
core:
  project_name: nn-template
  version: 0.0.1
  tags:
    - mytag

defaults:
  - hydra: default
  - nn: default
  - train: default
#    Decomment this parameter to get parallel job running
#  - hydra/launcher: joblib
